### ISSUE TITLE
Improve sub-pixel accuracy

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITKMontage#131]

**Comment by thewtex** [comment]
Add basic frequency-domain methods for subsample offset estimation. The frequency domain methods are summarized in 

  https://www.ncbi.nlm.nih.gov/pubmed/31352341

Implement two basic methods in an `itk::PhaseFrequencySubsampleCorrelationOptimizer`.

1. Power spectrum weighted mean. (Eqn. 10)
2. Slope of the phase-frequency least squares linear regression. (Eqn. 12)

Since the sample-level offset computation should be shared with the `itk::MaxPhaseCorrelationOptimizer` move its functionality into a common base class, `itk::SamplePeakCorrelationOptimizer`, including `MergePeaks`, `ZeroSuppression`, `PixelDistanceToTolerance`.

**Comment by thewtex** [comment]
Implementation in #146
